### ISSUE TITLE
Supports parsing custom Tableland functions

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/go-sqlparser#14] opened 2022-09-24 01:30 UTC
I came across a need for this when exploring the Royalty Rights idea, but it has come up in a couple other places as well. The problem is that there's no way to include the transaction hash of a write in an `INSERT` / `UPDATE` because the current transaction hash is not included in Solidities built-in variables (even though it is theoretically available: https://github.com/ethereum/EIPs/issues/901). 

@jsign had a nice idea to solve this where the validator does a replacement whenever it sees a magic custom SQL function. Quoting from Notion: 

---

> We could extend our SQL spec to invent a magic function TXN_HASH(). 

> When we parse the SQL statement, we can replace the TXN_HASH() call with the txn_hash.

> So.. inventing a custom function only usable in write-queries. This is resolved at “parsing time” transforming the query to something 100% compatible with SQLite; and then the execution pipeline is simply the same we have today. (i.e: parsing, walking the AST looking for TXN_HASH() calls, and replacing that with the txn_hash we know from the execution context in the validator)

> The benefit of this approach is that providing that building block can allow users to record the information in any way they want.

> e.g: users can do INSERT INTO XXXX VALUES ("Foo", TXN_HASH(), ...)

> It’s kind of filling the gap of Solidity not having a global func to get the txn_hash.

> So.. the power of the feature starts even at the dApp SC layer, since we can create SC libs that can assume this TXN_HASH() function can be used in SQL templates.

> Anyway, sharing some thought. Haven’t thought all angles of this; but I think sounds interesting.

---

I think this idea is worth exploring more. Opening this issue for that.

**Comment by jsign** [comment] 2022-10-25 18:17
@sanderpick , is this a duplicate of https://github.com/tablelandnetwork/go-tableland/issues/352 ?

**Comment by sanderpick** [comment] 2022-10-25 23:50
yep, i'll close this one

**Comment by carsonfarmer** [comment] 2022-11-15 19:04
Are we sure we want to close this one? We still need to support these functions in the parser, no?

**Comment by jsign** [comment] 2022-11-15 19:06
Yes, I'll reopen now that we have the strategy to create the issue on both sides.

**Closed** 2022-12-29 18:43 UTC
Labels: enhancement
